(defproject
  boot-project
  "0.0.0-SNAPSHOT"
  :repositories
  [["clojars" {:url "https://repo.clojars.org/"}]
   ["maven-central" {:url "https://repo1.maven.org/maven2"}]]
  :dependencies
  [[adzerk/boot-cljs "2.1.4" :scope "test"]
   [adzerk/boot-cljs-repl "0.3.3" :scope "test"]
   [buddy "2.0.0"]
   [ch.qos.logback/logback-classic "1.2.3"]
   [clj-time "0.14.2"]
   [cljs-ajax "0.7.3"]
   [compojure "1.6.0"]
   [conman "0.7.4"]
   [cprop "0.1.11"]
   [crisptrutski/boot-cljs-test "0.3.4" :scope "test"]
   [deraen/boot-sass "0.3.1" :scope "test"]
   [funcool/struct "1.1.0"]
   [luminus-http-kit "0.1.5"]
   [luminus-migrations "0.4.3"]
   [luminus-nrepl "0.1.4"]
   [luminus/ring-ttl-session "0.3.2"]
   [markdown-clj "1.0.1"]
   [metosin/compojure-api "1.1.11"]
   [metosin/muuntaja "0.4.1"]
   [metosin/ring-http-response "0.9.0"]
   [mount "0.1.11"]
   [org.clojure/clojure "1.8.0"]
   [org.clojure/clojurescript "1.9.946" :scope "provided"]
   [org.clojure/tools.cli "0.3.5"]
   [org.clojure/tools.logging "0.4.0"]
   [org.clojure/tools.reader "1.1.1"]
   [org.postgresql/postgresql "42.1.4"]
   [org.webjars.bower/tether "1.4.0"]
   [org.webjars/bootstrap "4.0.0-beta.2"]
   [org.webjars/font-awesome "4.7.0"]
   [ragtime "0.7.2"]
   [re-frame "0.10.2"]
   [reagent "0.7.0"]
   [reagent-utils "0.2.1"]
   [ring-webjars "0.2.0"]
   [ring/ring-core "1.6.3"]
   [ring/ring-defaults "0.3.1"]
   [secretary "1.2.3"]
   [selmer "1.11.3"]
   [onetom/boot-lein-generate "0.1.3" :scope "test"]]
  :source-paths
  ["src/cljs" "src/cljc" "src/clj"]
  :resource-paths
  ["resources"])