CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  passhash VARCHAR(80) NOT NULL,
  apikey VARCHAR(64) NOT NULL
);

--;;

CREATE TABLE notifications (
  id SERIAL PRIMARY KEY,
  owner INTEGER NOT NULL,
  userid INTEGER NOT NULL,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  sendtime TIMESTAMP NOT NULL,

  FOREIGN KEY (owner)
  REFERENCES users(id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);

--;;

CREATE TABLE tags (
  id SERIAL PRIMARY KEY,
  owner INTEGER NOT NULL,
  userid INTEGER NOT NULL,
  name TEXT NOT NULL,

  FOREIGN KEY (owner)
  REFERENCES users(id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);

--;;

CREATE TABLE notif_tag_join (
  id SERIAL PRIMARY KEY,

  notifid INTEGER NOT NULL
  REFERENCES notifications(id)
  ON UPDATE CASCADE
  ON DELETE RESTRICT,

  tagid INTEGER NOT NULL
  REFERENCES tags(id)
  ON UPDATE CASCADE
  ON DELETE RESTRICT,

  UNIQUE (notifid, tagid)
);